### ISSUE TITLE
Lab out of place in v6?

### ISSUE THREAD

**Issue by lizbur10** [learn-co-curriculum/react-initial-state-lab#15]
State hasn't been covered yet

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have moved this lab to the correct position, after state is introducted and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
